name: Update Nuclear snapcraft package

on: 
  workflow_dispatch:
  repository_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@master
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
      snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
    - name: Download .snap package
      run: |
        wget https://github.com/nukeop/nuclear/releases/download/nightly/nuclear-nightly.snap
    - name: Upload .snap package
      run: |
        snapcraft upload nuclear-nightly.snap --release stable
      