name: Update Nuclear snapcraft package

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v2
      with:
        snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
    - name: Download .snap package
      run: |
        wget https://github.com/nukeop/nuclear/releases/download/${{ github.event.client_payload.tag }}/nuclear-${{ github.event.client_payload.tag }}-amd64.snap
    - name: Upload .snap package
      run: |
        snapcraft upload nuclear-${{ github.event.client_payload.tag }}-amd64.snap --release stable
      
